[package]
name = "core"
version = "0.1.0"
authors = ["Denis K. <konsistentsi@gmail.com>"]
edition = "2018"

[dependencies]
rppal = "0.11"
rand = "0.8"
rs_ws281x = "0.4"
serialport = "3.3.0"
# serialport = "4.0"
